#Trabajad o morid gusanos >:)

nombre =input("Dame tu nombre: ")
date = input("Dame dame: ")
direccion= input("Dame tu direccion no por nada he >:) :")
tel = input("Dame dame: ")
DNI = input("Dame tu DNI: ")
cp = input("Dame dame: ")
Ciudad= input("En que ciudad vives?: ")
country = input("Dame dame tu pais: ")
